/* Auto-generated from LRC files — do not edit directly */
const LYRICS = {
  1: [
    {t:102.12, s:"The floor is soft like swallowed screams"},
    {t:107.64, s:"Each step disturbs the buried things"},
    {t:111.3, s:"The air it hums with secrets deep"},
    {t:111.8, s:"The air is thick, a breath I bite"},
    {t:115.28, s:"Afraid to wake what hides from light"},
    {t:126.24, s:"Lullaby"},
    {t:126.74, s:"Lullaby"},
    {t:130.24, s:"Drag me slow"},
    {t:134.24, s:"To the house where no light will show"},
    {t:141.32, s:"A whisper down the hall"},
    {t:141.82, s:"A place where even silence weeps"},
    {t:142.32, s:"The whispers twist"},
    {t:142.82, s:"They pull"},
    {t:143.32, s:"They plead"},
    {t:146.68, s:"It’s not my voice that speaks at all"},
    {t:147.18, s:"A voice that plants a wicked seed"},
    {t:157.8, s:"The mirrors crack but still they see"},
    {t:161.36, s:"Reflections not belonging to me"},
    {t:165.28, s:"The clocks they tick"},
    {t:165.78, s:"But time won’t flow"},
    {t:169.28, s:"This house it knows"},
    {t:169.78, s:"It always knows"},
    {t:177.6, s:"The candle flickers, dares to stay"},
    {t:181.34, s:"Though every shadow begs it stray"},
    {t:185.34, s:"I clutch it tight but do not move"},
    {t:189.2, s:"A hundred doors I dare not try"},
    {t:189.7, s:"Each door a truth I must not prove"},
    {t:202.3, s:"Lullaby"},
    {t:202.8, s:"Lullaby"},
    {t:203.3, s:"Lullaby"},
    {t:203.8, s:"Lullaby"},
    {t:205.02, s:"Drag me slow"},
    {t:205.52, s:"Drag me slow"},
    {t:208.8, s:"Each one leads where shadows cry"},
    {t:209.3, s:"To the house where no light will show"},
    {t:209.8, s:"To the house where no light will show"},
    {t:210.8, s:"My name"},
    {t:216.44, s:"No dawn will come, no voices call"},
    {t:221.66, s:"I wait alone"},
    {t:221.993, s:"And fear it all"},
  ],
  2: [
    {t:7.54, s:"Ghost appeared in my bedroom"},
    {t:8.04, s:"Giant shadow that spread through the walls"},
    {t:16.3, s:"I was so scared of you"},
    {t:16.8, s:"But now I know I'm in charge of it all"},
    {t:22.88, s:"You're just a ghost"},
    {t:23.38, s:"But I'm the one who dreams"},
    {t:23.88, s:"You're just a ghost"},
    {t:30.4, s:"And I decide what’s real"},
    {t:30.9, s:"You're just a ghost"},
    {t:38.34, s:"In the dark behind the scenes"},
    {t:38.84, s:"You're just a ghost"},
    {t:46.44, s:"But I'm the one who leads"},
    {t:55.66, s:"Standing over my head now"},
    {t:56.16, s:"Oh my God how did you get so tall?"},
    {t:64.06, s:"All my life I've been let down"},
    {t:64.56, s:"But I know I'm in charge of it all"},
    {t:70.22, s:"You're just a ghost"},
    {t:70.72, s:"But I'm the one who dreams"},
    {t:71.22, s:"You're just a ghost"},
    {t:78.5, s:"And I decide what’s real"},
    {t:79, s:"You're just a ghost"},
    {t:86.5, s:"In the dark behind the scenes"},
    {t:87, s:"You're just a ghost"},
    {t:92.97999999999999, s:"But I'm the one who leads"},
    {t:106.16, s:"I tell myself it's nothing"},
    {t:106.66, s:"Just a shape behind the door"},
    {t:114.28, s:"But I still leave the light on"},
    {t:114.78, s:"And sleep curled on the floor"},
    {t:123.5, s:"It’s not the ghost that haunts me"},
    {t:124, s:"It’s the fear I let it feed"},
    {t:131.98, s:"I should be stronger"},
    {t:132.48, s:"But I'm still too scared to breathe"},
    {t:140.52, s:"Some nights I speak like a fighter"},
    {t:141.02, s:"Then I choke when the silence crawls"},
    {t:149.1, s:"I say it’s just in my head"},
    {t:149.6, s:"But I’ve built it ten feet tall"},
    {t:156.86, s:"Every time I close my eyes"},
    {t:157.36, s:"I see the ways I’ve failed"},
    {t:163.24, s:"I keep hoping you'll leave me"},
    {t:163.74, s:"But I always feed the fear I hate"},
    {t:172.34, s:"You're just a ghost"},
    {t:172.84, s:"But I gave you a throne"},
    {t:173.34, s:"You're just a ghost"},
    {t:180.28, s:"Still I face you alone"},
    {t:180.78, s:"You're just a ghost"},
    {t:188.24, s:"But you know where I bleed"},
    {t:188.74, s:"You're just a ghost"},
    {t:196.34, s:"And I can't seem to lead"},
  ],
  3: [
    {t:10.86, s:"The air is thin it cuts like glass"},
    {t:11.36, s:"A fragile echo of the past"},
    {t:22.42, s:"Static whispers crack the frame"},
    {t:22.92, s:"A hollow hum that calls my name"},
    {t:30.34, s:"Falling slow in the velvet night"},
    {t:30.84, s:"The world distorts in shattered glow"},
    {t:31.34, s:"Contours fading don't let go"},
    {t:37.36, s:"Dancing on the wire of dreams"},
    {t:37.86, s:"Fragile silence ripped at seams"},
    {t:52.36, s:"Breathing shadows as they bite"},
    {t:52.86, s:"Glitching stars and foggy skies"},
    {t:53.36, s:"I feel alive as the moment dies"},
    {t:64.34, s:"Eyelids flicker neon hue"},
    {t:64.84, s:"Colors bleed but can't push through"},
    {t:71.7, s:"Static kisses bruised with grace"},
    {t:72.2, s:"Every step rewrites this place"},
    {t:81.12, s:"A memory burns like ultraviolet flame"},
    {t:81.62, s:"A fractured picture without a name"},
    {t:97.56, s:"The chaos sings a lullaby"},
    {t:98.06, s:"Hold my breath don't let us die"},
    {t:105.34, s:"Dancing on the wire of dreams"},
    {t:105.84, s:"Fragile silence ripped at seams"},
    {t:120.38, s:"Glitching stars and foggy skies"},
    {t:120.713, s:"I feel alive as the moment dies"},
  ],
  4: [
    {t:0, s:"I am falling through a hypercube"},
    {t:0.5, s:"Wonder what I'm doing"},
    {t:5.68, s:"Think I need a hobby"},
    {t:6.18, s:"What's the point of doing nothing all the time"},
    {t:14.82, s:"These hypercubes are filling up my dreams"},
    {t:15.32, s:"It's becoming lucid"},
    {t:20.84, s:"Starting to enjoy it"},
    {t:21.34, s:"Now I'm meeting creatures that are not of this world"},
    {t:26.98, s:"Do I say hello to them"},
    {t:27.48, s:"Or should I just ignore"},
    {t:33.22, s:"Maybe I should fight them"},
    {t:33.72, s:"Or I could just tame them"},
    {t:38.42, s:"What should I do"},
    {t:38.92, s:"How should I know"},
    {t:44.58, s:"I just want to know"},
    {t:45.08, s:"How to greet them"},
    {t:50.26, s:"In this plane of reality"},
    {t:50.76, s:"We're just prisoners of matter"},
    {t:56.14, s:"You think we're meant for more"},
    {t:56.64, s:"Than what we can imagine"},
    {t:61.24, s:"What if these creatures"},
    {t:61.74, s:"Exist beyond our dimension"},
    {t:67.08, s:"And I'm the one trespassing"},
    {t:67.58, s:"In this universe"},
    {t:68.08, s:"It's an infinite cycle"},
    {t:73.28, s:"That never ends"},
    {t:73.78, s:"That never ends"},
    {t:86.82, s:"Do I say hello to them"},
    {t:87.32, s:"Or should I just ignore"},
    {t:93.44, s:"Maybe I should fight them"},
    {t:93.94, s:"Or I could just tame them"},
    {t:99.16, s:"What should I do"},
    {t:99.66, s:"How should I know"},
    {t:101.94, s:"I just want to know"},
    {t:102.44, s:"How to greet them"},
    {t:102.94, s:"How to greet them"},
    {t:103.44, s:"How to greet them"},
    {t:108.84, s:"In this plane of reality"},
    {t:112.74, s:"Do I say hello to them"},
    {t:113.24, s:"Or should I just ignore"},
    {t:117.32, s:"Maybe I should fight them"},
    {t:117.82, s:"Or I could just tame them"},
    {t:120.9, s:"What should I do"},
    {t:121.4, s:"How should I know"},
    {t:123.32, s:"I just want to know"},
    {t:123.82, s:"How to greet them"},
    {t:124.32, s:"How to greet them"},
    {t:124.82, s:"How to greet them"},
    {t:132.7, s:"In this plane of reality"},
    {t:133.2, s:"We're just prisoners of matter"},
    {t:137.22, s:"You think we're meant for more"},
    {t:137.72, s:"Than what we can imagine"},
    {t:143.28, s:"What if these creatures"},
    {t:143.78, s:"Exist beyond our dimension"},
    {t:149.12, s:"And I'm the one trespassing"},
    {t:149.62, s:"In this universe"},
    {t:150.12, s:"It's an infinite cycle"},
    {t:156.74, s:"That never ends"},
    {t:157.073, s:"That never ends"},
  ],
  5: [
    {t:0, s:"I smile in the mirror, but it cracks at the edge"},
    {t:13.66, s:"Comparing my shadow to someone else's ledge"},
    {t:17.82, s:"They’re louder, brighter, walking taller than I do"},
    {t:22.4, s:"And I shrink in the silence, just trying to break through"},
    {t:27.34, s:"I wear confidence like it’s borrowed for a day"},
    {t:27.84, s:"Folded at the seams, always slipping away"},
    {t:36.94, s:"I feel smaller than I should,"},
    {t:37.44, s:"Like I’m never enough, even when I’m good"},
    {t:46.34, s:"Living in the echo of someone else’s praise"},
    {t:46.84, s:"Trapped in the maze of my own sideways gaze"},
    {t:55.14, s:"But maybe there's more to me"},
    {t:55.64, s:"Than the doubt I let the world see"},
    {t:68.7, s:"I walk with a whisper while they run with a roar"},
    {t:69.2, s:"Measuring my worth by the cracks in the floor"},
    {t:78.62, s:"A thousand eyes and none of them mine"},
    {t:79.12, s:"Caught in a race where I fall behind"},
    {t:87.7, s:"Their stars burn loud while I fade to gray"},
    {t:88.2, s:"But I'm still here—won’t look away"},
    {t:97.62, s:"I feel smaller than I should,"},
    {t:98.12, s:"Like I’m never enough, even when I’m good"},
    {t:106.36, s:"Living in the echo of someone else’s praise"},
    {t:106.86, s:"Trapped in the maze of my own sideways gaze"},
    {t:115.76, s:"But maybe there's more to me"},
    {t:116.26, s:"Than the doubt I let the world see"},
    {t:129.88, s:"Every flaw I counted twice"},
    {t:130.38, s:"Was just a mirror bending light"},
    {t:137.82, s:"What if I’m not broken, just bruised?"},
    {t:138.32, s:"Not weak—just confused?"},
    {t:148.56, s:"I felt smaller than I should"},
    {t:149.06, s:"But maybe now, I’m learning I’m still good"},
    {t:157.82, s:"I’ll rise from the echo, find my own voice"},
    {t:158.32, s:"Stop seeing myself as the lesser choice"},
    {t:166.94, s:"'Cause maybe there's strength in me"},
    {t:167.44, s:"That I never dared believe"},
    {t:181.66, s:"Echoes fade, but I'm still here"},
    {t:182.16, s:"Not quite loud, but I’m aware"},
    {t:190.08, s:"Every crack wrote my story"},
    {t:190.413, s:"Tracing proof that I survived"},
  ],
  6: [
    {t:0, s:"I'm gonna be honest"},
    {t:0.5, s:"I wake up in the mornin'"},
    {t:12.16, s:"And everything is the same"},
    {t:12.66, s:"Just playin' my game"},
    {t:16.18, s:"Like I always do"},
    {t:16.68, s:"Keepin' my cool"},
    {t:19.48, s:"The moment I'm unconscious"},
    {t:19.98, s:"I get so pretentious"},
    {t:26.04, s:"I'm not a little bit"},
    {t:26.54, s:"The same person"},
    {t:27.04, s:"That I was"},
    {t:32.26, s:"Between dreams and reality"},
    {t:32.76, s:"There's a chasm of galaxies"},
    {t:39.48, s:"Two different people are asleep"},
    {t:39.98, s:"Inside of me"},
    {t:40.48, s:"Inside of me"},
    {t:44.74, s:"Between dreams and reality"},
    {t:50.08, s:"There's a chasm of galaxies"},
    {t:50.58, s:"Two different people are asleep"},
    {t:56.28, s:"Inside of me"},
    {t:56.78, s:"Inside of me"},
    {t:59.84, s:"Don't know how to be honest"},
    {t:60.34, s:"When I'm not unconscious"},
    {t:65.98, s:"I don't even know"},
    {t:66.48, s:"Who I am"},
    {t:66.98, s:"Who I was"},
    {t:67.48, s:"So I do what I do"},
    {t:67.98, s:"And I try to stay cool"},
    {t:73.22, s:"But when I wake up in the mornin'"},
    {t:73.72, s:"I'm back where I started"},
    {t:76.8, s:"And all that I got is the time that I lost"},
    {t:77.3, s:"And the things that I did"},
    {t:81.5, s:"But they don't even matter"},
    {t:82, s:"And I don't even know"},
    {t:84.94, s:"And I can't even tell you"},
    {t:85.44, s:"Between dreams and reality"},
    {t:89.8, s:"There's a chasm of galaxies"},
    {t:90.3, s:"Two different people are asleep"},
    {t:96.56, s:"Inside of me"},
    {t:97.06, s:"Inside of me"},
    {t:100.88, s:"Between dreams and reality"},
    {t:101.38, s:"There's a chasm of galaxies"},
    {t:107.68, s:"Two different people are asleep"},
    {t:108.055, s:"Inside of me"},
    {t:108.43, s:"Inside of me"},
  ],
  7: [
    {t:0, s:"I danced with shadows they laughed so loud"},
    {t:10, s:"The moon was a spotlight on my awkward crowd"},
    {t:20.34, s:"Hands like puppets pulling my strings"},
    {t:30.5, s:"Tickling nightmares with embered wings"},
    {t:36.08, s:"Oh I’m the king of my own bad dream"},
    {t:40.62, s:"Clown shoes squishing in a foggy stream"},
    {t:44.66, s:"The fools all chant and call my name"},
    {t:49.28, s:"But hey at least I own my shame"},
    {t:54.3, s:"A chandelier of spiders lit my room"},
    {t:63.82, s:"Dripping sarcasm their webs like doom"},
    {t:72.46000000000001, s:"Can’t run these marshmallow legs won’t go"},
    {t:80.82, s:"Who trips in fear at their own one-man show"},
    {t:90.53999999999999, s:"Mirror’s cracking it’s got jokes today"},
    {t:94.12, s:"Shows me wearing my fear like a cabaret"},
    {t:98.08, s:"Mocking my shriek as I stumble blind"},
    {t:102.53999999999999, s:"I’m a punchline monster one of a kind"},
    {t:106.78, s:"Oh I’m the king of my own bad dream"},
    {t:111.02000000000001, s:"Clown shoes squishing in a foggy stream"},
    {t:115.1, s:"The fools all chant and call my name"},
    {t:119.52000000000001, s:"But hey at least I own my shame"},
    {t:124.34, s:"Oh the night paints faces with crooked art"},
    {t:131.16, s:"Wolves in ballet or wasps with harp"},
    {t:137.16, s:"I laugh out loud till I can barely see"},
    {t:141.52, s:"Turns out the villain is just... still me"},
  ],
  8: [
    {t:0, s:"(Tell me what I want to hear)"},
    {t:0.5, s:"(Only what I want to hear)"},
    {t:8.4, s:"Crystal Ball on my shelf collecting time"},
    {t:12.84, s:"Spinning fortunes, yours and mine"},
    {t:16.96, s:"Used to hang on every scene you'd show"},
    {t:22, s:"Till you lit up storms where sun should glow"},
    {t:26.56, s:"Now I'm picking through your imagery"},
    {t:28.9, s:"Only seeing what suits me"},
    {t:29.4, s:"'Cause reality's what I decide"},
    {t:35.78, s:"And I'm rewriting all the lines"},
    {t:40.02, s:"Why'd you have to show me things I didn't ask to see?"},
    {t:44.58, s:"Now you're gathering dust, just let me be"},
    {t:58.26, s:"Who needs your crystal answers?"},
    {t:67.7, s:"Tuesday's visions felt so right"},
    {t:68.2, s:"Wednesday’s glimpse gave me a fright"},
    {t:72, s:"Selective seeing's all I've got"},
    {t:72.5, s:"Believing half and half forgot"},
    {t:76.68, s:"Paint my future in my mind"},
    {t:77.18, s:"Leave your warnings far behind"},
    {t:81.06, s:"'Cause reality's what I create"},
    {t:84.82, s:"And I'm tired of tempting fate"},
    {t:88.42, s:"Why'd you have to show me things I didn't want to know?"},
    {t:93.03999999999999, s:"Now you're gathering dust, I'll let you go"},
    {t:98.7, s:"When I can make my own"},
    {t:99.2, s:"Who needs your crystal answers?"},
    {t:99.7, s:"Who needs your crystal answers?"},
    {t:100.2, s:"When I can make my own"},
    {t:100.7, s:"Who needs your crystal answers?"},
    {t:113.18, s:"I'd rather be unknown"},
    {t:113.68, s:"I'd rather be unknown"},
    {t:117.26, s:"(Dust, dust, gathering dust)"},
    {t:117.76, s:"(Truth, truth, what is truth?)"},
    {t:122.26, s:"I'll write my own tomorrow"},
    {t:122.76, s:"I'll choose what to believe"},
    {t:126.56, s:"(Dust, dust, gathering dust)"},
    {t:127.06, s:"(Truth, truth, what is truth?)"},
    {t:131.26, s:"Once divine, now just a glass"},
    {t:131.76, s:"A faded light I let drift past"},
    {t:135.74, s:"Thursday brought a fractured view"},
    {t:136.24, s:"Friday's vision cut right through"},
    {t:139.92, s:"The cracks revealed the things I feared"},
    {t:140.42, s:"The voices that I never cleared"},
    {t:144.5, s:"I begged for lies in softer tones"},
    {t:145, s:"But silence chilled me to the bones"},
    {t:149.02, s:"Your crystal truths I used to bend"},
    {t:149.52, s:"Now echo what I can't defend"},
    {t:153.54, s:"Every glare reflects my face"},
    {t:154.04, s:"In truths I tried so hard to chase"},
    {t:158.06, s:"But now they burn, now they sting"},
    {t:158.56, s:"Revealing every hidden thing"},
    {t:162.62, s:"The future’s fog, the past is near"},
    {t:163.12, s:"And nothing’s what it seemed, my dear"},
    {t:167.16, s:"The mirror shows what I can't flee"},
    {t:167.66, s:"Your crystal was just showing me"},
    {t:171.72, s:"Who needs your crystal answers?"},
    {t:172.22, s:"You’ve said enough for me"},
    {t:172.72, s:"Who needs your crystal answers?"},
    {t:180.56, s:"Now you're just glass to see"},
    {t:189.8, s:"I see what I want to see"},
    {t:190.3, s:"Build a world that comforts me"},
    {t:194.24, s:"Truth’s a ghost I chased away"},
    {t:194.74, s:"But it still finds me, day by day"},
    {t:198.82, s:"If belief can bend what’s real"},
    {t:199.32, s:"Then what's imagined, what’s revealed?"},
    {t:203.3, s:"Your crystal ball showed all too clear—"},
    {t:203.8, s:"I never wanted truth too near"},
    {t:207.94, s:"Who needs your crystal answers?"},
    {t:208.44, s:"You’ve said enough for me"},
    {t:208.94, s:"Who needs your crystal answers?"},
    {t:216.94, s:"Now you're just glass to see"},
  ],
  9: [
    {t:0, s:"In the dark where shadows crawl"},
    {t:3.78, s:"A towering ghost stands tall"},
    {t:7.1, s:"It loomed above with hollow scream"},
    {t:10.12, s:"But I knew this was my dream"},
    {t:15.18, s:"I’m the ruler of the night"},
    {t:18.5, s:"In my mind I hold the fight"},
    {t:21.88, s:"Monsters bow and chaos fades"},
    {t:24.96, s:"I command these haunted shades"},
    {t:26.96, s:"[Verse 2]"},
    {t:35.38, s:"Its hands stretched high to touch the sky"},
    {t:38, s:"Its hollow gaze met my eye"},
    {t:41.5, s:"But fear was not my melody"},
    {t:45, s:"This dream bends and answers me"},
    {t:47.7, s:"I’m the ruler of the night"},
    {t:51.16, s:"In my mind I hold the fight"},
    {t:54.54, s:"Monsters bow and chaos fades"},
    {t:57.56, s:"I command these haunted shades"},
    {t:61.04, s:"With a snap the ghost dissolved"},
    {t:64.5, s:"Every fear and doubt absolved"},
    {t:67.82, s:"I rewrite the midnight script"},
    {t:70.46000000000001, s:"In my dream I hold the grip"},
    {t:74.56, s:"Now the shadows dance and sing"},
    {t:77.16, s:"No longer ruled by fright they cling"},
    {t:80.3, s:"I paint the stars and shape the air"},
    {t:83.88, s:"This is my world I declare"},
    {t:86.86, s:"I’m the ruler of the night"},
    {t:90.44, s:"In my mind I hold the fight"},
    {t:93.82, s:"Monsters bow and chaos fades"},
    {t:96.82, s:"I command these haunted shades"},
    {t:99.94, s:"I refuse to lose, refuse to cower"},
    {t:103.22, s:"Won’t let fear take away my power"},
    {t:106.46000000000001, s:"This dream is mine, I built the frame"},
    {t:109.62, s:"And every shadow knows my name"},
    {t:112.97999999999999, s:"My dream is my unconscious sea"},
    {t:116.25999999999999, s:"It holds the echoes deep in me"},
    {t:119.64, s:"The dark, the light, the in-between"},
    {t:122.44, s:"The things I’ve felt, the things unseen"},
    {t:126.12, s:"This dream is mine, I drew the line"},
    {t:129.3, s:"Between the fear and the divine"},
    {t:132.42, s:"That’s why I’m ruler, why I stand"},
    {t:135.56, s:"The owner of this shadowland"},
    {t:149.16, s:"This is my world I declare"},
  ],
};
